// One check case per scanner that runs an installed tool: the smallest
// input that makes the tool report a finding, taken from the real-binary
// adapter tests (packages/scanners/test/*.subprocess.test.ts). A preinstall
// (preinstall.ts) runs each one to prove the tool it installed executes and
// reports through its adapter. The end-to-end tests run every case through
// the real binaries, so a case that stops matching fails there first.
import { randomBytes } from "node:crypto";
import type { BuiltinScanner } from "@openqodex/core";

export type CheckCase = {
  scanner: BuiltinScanner;
  // The rule the scanner reports on `anchor`. Null for cargo-deny: its
  // findings need the crates of a lockfile in the Cargo cache, which no
  // shipped input can bring, so its case proves only that it runs (the
  // advisory database fetch and a check of a project with no dependencies).
  rule: string | null;
  anchor: string | null;
  // The scanner needs the network to run (rule packs, advisories, schemas).
  network?: true;
  // The files of the case, made fresh for each run: gitleaks' secret is
  // generated, never shipped.
  files(): Record<string, string>;
};

const fixed = (files: Record<string, string>) => () => files;

// An SSH port open to every address.
const OPEN_SSH = `resource "aws_security_group" "web" {
  name        = "web"
  description = "web access"

  ingress {
    description = "ssh"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
`;

// A privileged container.
const PRIVILEGED_POD = `apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: web
      image: nginx:1.27
      securityContext:
        privileged: true
`;

// A Deployment whose container runs privileged.
const PRIVILEGED_DEPLOYMENT = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx:1.27.3
          securityContext:
            privileged: true
`;

// Every builtin scanner but the in-process sqllint, which installs nothing.
export const CHECK_CASES: Readonly<Record<Exclude<BuiltinScanner, "sqllint">, CheckCase>> = {
  semgrep: {
    scanner: "semgrep",
    rule: "python.lang.security.audit.formatted-sql-query.formatted-sql-query",
    anchor: "search.py",
    network: true,
    files: fixed({
      "search.py": `import sqlite3
from flask import request
def query():
    user = request.args.get("name")
    db = sqlite3.connect("test.db")
    return db.execute(f"SELECT * FROM users WHERE name = '{user}'")
`,
    }),
  },
  gitleaks: {
    scanner: "gitleaks",
    rule: "stripe-access-token",
    anchor: "config.py",
    files: () => ({ "config.py": `STRIPE_KEY = 'sk_live_${randomBytes(12).toString("hex")}'\n` }),
  },
  squawk: {
    scanner: "squawk",
    rule: "require-concurrent-index-creation",
    anchor: "db/migrations/0002_orders.sql",
    files: fixed({ "db/migrations/0002_orders.sql": "CREATE INDEX orders_customer_idx ON orders (customer_id);\n" }),
  },
  sqlfluff: {
    scanner: "sqlfluff",
    rule: "CV05",
    anchor: "reports/active_users.sql",
    files: fixed({ "reports/active_users.sql": "SELECT id FROM users WHERE deleted_at = NULL;\n" }),
  },
  "osv-scanner": {
    scanner: "osv-scanner",
    rule: "GHSA-p6mc-m468-83gw",
    anchor: "package-lock.json",
    network: true,
    files: fixed({
      "package-lock.json": JSON.stringify({ name: "tiny", lockfileVersion: 2, packages: { "": { name: "tiny" }, "node_modules/lodash": { version: "4.17.15" } } }, null, 2),
    }),
  },
  "cargo-deny": {
    scanner: "cargo-deny",
    rule: null,
    anchor: null,
    network: true,
    files: fixed({
      "Cargo.toml": '[package]\nname = "tiny"\nversion = "0.1.0"\nedition = "2021"\n',
      "Cargo.lock": '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n\n[[package]]\nname = "tiny"\nversion = "0.1.0"\n',
      "src/main.rs": "fn main() {}\n",
    }),
  },
  actionlint: {
    scanner: "actionlint",
    rule: "expression",
    anchor: ".github/workflows/ci.yml",
    files: fixed({ ".github/workflows/ci.yml": "on: pull_request\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ${{ github.event.pull_request.title }}\n" }),
  },
  zizmor: {
    scanner: "zizmor",
    rule: "template-injection",
    anchor: ".github/workflows/greet.yml",
    files: fixed({
      ".github/workflows/greet.yml": `on: pull_request
permissions: {}
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "\${{ github.event.pull_request.title }}"
`,
    }),
  },
  hadolint: { scanner: "hadolint", rule: "DL3007", anchor: "Dockerfile", files: fixed({ Dockerfile: "FROM python:latest\n" }) },
  trivy: { scanner: "trivy", rule: "AWS-0107", anchor: "infra/main.tf", files: fixed({ "infra/main.tf": OPEN_SSH }) },
  checkov: { scanner: "checkov", rule: "CKV_K8S_16", anchor: "k8s/pod.yaml", files: fixed({ "k8s/pod.yaml": PRIVILEGED_POD }) },
  tflint: {
    scanner: "tflint",
    rule: "terraform_unused_declarations",
    anchor: "infra/variables.tf",
    files: fixed({ "infra/variables.tf": 'variable "region" {\n  type = string\n}\n' }),
  },
  "kube-linter": { scanner: "kube-linter", rule: "privileged-container", anchor: "k8s/web.yaml", files: fixed({ "k8s/web.yaml": PRIVILEGED_DEPLOYMENT }) },
  kubeconform: {
    scanner: "kubeconform",
    rule: "type",
    anchor: "k8s/web.yaml",
    network: true,
    files: fixed({ "k8s/web.yaml": PRIVILEGED_DEPLOYMENT.replace("replicas: 1", 'replicas: "2"') }),
  },
  shellcheck: { scanner: "shellcheck", rule: "SC2086", anchor: "deploy.sh", files: fixed({ "deploy.sh": "#!/bin/sh\necho $FOO\n" }) },
  ruff: { scanner: "ruff", rule: "F401", anchor: "main.py", files: fixed({ "main.py": "import os\n" }) },
  brakeman: {
    scanner: "brakeman",
    rule: "SQL",
    anchor: "app/controllers/users_controller.rb",
    files: fixed({
      Gemfile: "source 'https://rubygems.org'\ngem 'rails'\n",
      "config/application.rb": "require 'rails/all'\nmodule Tiny\n  class Application < Rails::Application\n  end\nend\n",
      "app/controllers/users_controller.rb": "class UsersController < ApplicationController\n  def index\n    User.where(\"name = '#{params[:name]}'\")\n  end\nend\n",
    }),
  },
  rubocop: { scanner: "rubocop", rule: "Lint/UselessAssignment", anchor: "app.rb", files: fixed({ "app.rb": "unused = 1\n" }) },
  bandit: {
    scanner: "bandit",
    rule: "B608",
    anchor: "search.py",
    files: fixed({ "search.py": "def query(user):\n    return f'SELECT * FROM users WHERE name = {user}'\n" }),
  },
  oxlint: { scanner: "oxlint", rule: "eslint/no-debugger", anchor: "main.js", files: fixed({ "main.js": "debugger;\n" }) },
  golangci: {
    scanner: "golangci",
    rule: "gosec",
    anchor: "main.go",
    files: fixed({ "go.mod": "module example.com/tiny\n\ngo 1.22\n", "main.go": 'package main\nimport "crypto/md5"\nfunc main() { _ = md5.New() }\n' }),
  },
};

// The check case of a scanner, or null for one that installs nothing.
export function checkCase(scanner: BuiltinScanner): CheckCase | null {
  return scanner === "sqllint" ? null : CHECK_CASES[scanner];
}
